# Generated by Django 4.2.6 on 2024-10-28 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol_app', '0001_initial'),
        ('persona_app', '0007_alter_persona_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('trabajador_ley', models.BooleanField(default=False)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('tipo_usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Usuario')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol_app.rol')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario_rol',
                'verbose_name_plural': 'Usuarios_Roles',
                'ordering': ['usuario'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ManyToManyField(through='usuario_app.UsuarioRol', to='rol_app.rol'),
        ),
    ]
