# Generated by Django 4.2.6 on 2024-01-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol_app', '0001_initial'),
        ('usuario_app', '0002_remove_usuario_rol_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ManyToManyField(through='usuario_app.UsuarioRol', to='rol_app.rol'),
        ),
    ]
