# Generated by Django 4.2.6 on 2024-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
