# Generated by Django 4.2.6 on 2024-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='religion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estado', models.CharField(default=False, max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'religion',
                'verbose_name_plural': 'religion',
                'ordering': ['nombre'],
            },
        ),
    ]
