# Generated by Django 4.2.6 on 2024-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_persona_udg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_persona_udg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
