# Generated by Django 4.2.6 on 2023-10-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombres')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
    ]
