# Generated by Django 4.2.6 on 2023-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_atencion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_atencion',
            options={'ordering': ['nombre'], 'verbose_name': 'tipo_atencion', 'verbose_name_plural': 'Tipo de Atencion'},
        ),
    ]
