# Generated by Django 4.2.6 on 2023-11-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_atencion_app', '0002_alter_tipo_atencion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atencion',
            name='estado',
            field=models.CharField(default=False, max_length=255, verbose_name='Estado'),
        ),
    ]
