# Generated by Django 4.2.6 on 2024-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_atencion_app', '0003_alter_tipo_atencion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atencion',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
