# Generated by Django 4.2.6 on 2024-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_atencion_app', '0004_alter_tipo_atencion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_atencion',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria'),
        ),
    ]
