# Generated by Django 4.2.6 on 2024-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_atencion_app', '0006_remove_tipo_atencion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atencion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
