"""
Django settings for sigi_leip_project project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(uj15hzgdh^#qk_h&*yfa6vzgy=enye6vx6!)#l2iy27ey5ji$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tipo_atencion_app',
    'tipo_instrumento_psicologico_app',
    'configuracion_app',
    'usuario_app',
    'persona_app',
    'estado_app',
    'municipio_app',
    'rol_app',
    'ingreso_familiar_app',
    'licenciatura_app',
    'semestre_app',
    'estado_atencion_app',
    'institucion_app',
    'vive_con_app',
    'vive_en_app',
    'categoria_trastorno_app',
    'grupo_trastorno_app',
    'diagnostico_app',
    'grado_academico_app',
    'atencion_psicologica_app',
    'horarios_app',
    'motivo_consulta_app',
    'asignar_app',
    'disponibilidad_horario_consulta_app',
    'seguimiento_atencion_app',
    'eval_psico_mst_nivel1_app',
    'eval_psico_fpp_app',
    'eval_psico_ssi_beck_app',
    'eval_psico_autoevaluacion_app',
    'taller_app',
    'valoracion_app',
    'eval_psico_mst_nivel2_app',
    'religion_app',
    'estado_civil_app',
    'historia_clinica_app',
    'tipo_persona_udg_app',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuario_app.middleware.closeSession',
]

ROOT_URLCONF = 'sigi_leip_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigi_leip_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sigi_leip',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'POST': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'usuario_app.Usuario'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (BASE_DIR, 'static')
# STATICFILES_DIRS = [
#     'D:/TRABAJO/Proyectos/Django/sigi_leip/configuracion_sistema_app/templates/recursos']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# tiempo de vida de la sesion en segundos
#SESSION_COOKIE_AGE = 600

# para que expire la sesion al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGIN_URL = "/accounts/login/"

# tiempo en minutos de activa la sesion
AUTO_LOGOUT_TIME = 30
