# Generated by Django 4.2.6 on 2024-06-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona_app', '0007_alter_persona_direccion'),
        ('institucion_app', '0001_initial'),
        ('atencion_psicologica_app', '0003_atencion_diagnostico_dsm5_and_more'),
        ('taller_app', '0003_alter_taller_especialista'),
        ('tipo_atencion_app', '0005_tipo_atencion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_valoracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha valoracion')),
                ('tipo_institucion', models.CharField(max_length=255, verbose_name='Tipo institucion')),
                ('atencion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica')),
                ('institucion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucion_app.institucion')),
            ],
            options={
                'verbose_name': 'valoracion',
                'verbose_name_plural': 'Valoracion',
                'ordering': ['fecha_valoracion'],
            },
        ),
        migrations.CreateModel(
            name='valoracion_taller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller_app.taller')),
                ('valoracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valoracion_app.valoracion')),
            ],
            options={
                'verbose_name': 'valoracion_taller',
                'verbose_name_plural': 'valoracion_taller',
                'ordering': ['valoracion'],
            },
        ),
        migrations.AddField(
            model_name='valoracion',
            name='taller',
            field=models.ManyToManyField(through='valoracion_app.valoracion_taller', to='taller_app.taller'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='tipo_atencion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_atencion_app.tipo_atencion'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='valorado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona'),
        ),
    ]
