# Generated by Django 4.2.6 on 2024-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estado', models.CharField(default=False, max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'semestre',
                'verbose_name_plural': 'Semestre',
                'ordering': ['nombre'],
            },
        ),
    ]
