# Generated by Django 4.2.6 on 2023-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_instrumento_psicologico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_instrumento_psicologico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'tipo_instrumento_psicologico',
                'verbose_name_plural': 'Tipo de Instrumento Psicologico',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='tipo_atencion',
        ),
    ]
