# Generated by Django 4.2.6 on 2023-12-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_instrumento_psicologico_app', '0002_tipo_instrumento_psicologico_delete_tipo_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_instrumento_psicologico',
            name='estado',
            field=models.CharField(default=False, max_length=255, verbose_name='Estado'),
        ),
    ]
