# Generated by Django 4.2.6 on 2024-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_instrumento_psicologico_app', '0003_alter_tipo_instrumento_psicologico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_instrumento_psicologico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
