# Generated by Django 4.2.6 on 2023-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('segundo_nombre', models.CharField(max_length=255, verbose_name='Segundo nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('segundo_apellido', models.CharField(max_length=255, verbose_name='Segundo apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('sexo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('nombre_emergencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre emergencia')),
                ('parentesco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parentesco')),
                ('telefono_responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono del responsable')),
                ('nombre_responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del responsable')),
                ('tipo_usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
    ]
