# Generated by Django 4.2.6 on 2023-12-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipio_app', '0001_initial'),
        ('estado_app', '0001_initial'),
        ('persona_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_udg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código UDG'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipio_app.municipio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona_udg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de persona UDG'),
        ),
    ]
