# Generated by Django 4.2.6 on 2023-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0002_remove_persona_tipo_usuario_persona_codigo_udg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='telefono_responsable',
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono de emergencia'),
        ),
    ]
