# Generated by Django 4.2.6 on 2023-12-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0003_remove_persona_telefono_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
