# Generated by Django 4.2.6 on 2023-12-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0004_persona_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
