# Generated by Django 4.2.6 on 2024-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0007_alter_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Genero'),
        ),
    ]
