# Generated by Django 4.2.6 on 2024-11-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_persona_udg_app', '0001_initial'),
        ('persona_app', '0008_persona_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona_udg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_persona_udg_app.tipo_persona_udg'),
        ),
    ]
