# Generated by Django 4.2.6 on 2024-01-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vive_en',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vive_en', models.CharField(max_length=255, verbose_name='Vive en')),
                ('estado', models.CharField(default=False, max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'vive_en',
                'verbose_name_plural': 'Vive en',
                'ordering': ['vive_en'],
            },
        ),
    ]
