# Generated by Django 4.2.6 on 2024-11-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0014_historia_clinica_vive_en'),
        ('vive_en_app', '0004_alter_vive_en_model_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vive_en_model',
            new_name='vive_en',
        ),
    ]
