# Generated by Django 4.2.6 on 2024-04-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion_psicologica_app', '0002_alter_atencion_psicologica_options'),
        ('persona_app', '0007_alter_persona_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('hora', models.DateTimeField(verbose_name='Hora')),
                ('tipo_persona', models.CharField(max_length=255, verbose_name='Tipo Persona')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica')),
                ('persona_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona')),
            ],
            options={
                'verbose_name': 'asinar',
                'verbose_name_plural': 'Asignar',
                'ordering': ['id'],
            },
        ),
    ]
