# Generated by Django 4.2.6 on 2024-04-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignar',
            name='hora',
            field=models.CharField(max_length=255, verbose_name='Hora'),
        ),
    ]
