# Generated by Django 4.2.6 on 2024-09-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0002_caracteristicas_infancia_adolescencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas_infancia_adolescencia',
            name='hc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica_app.historia_clinica'),
        ),
    ]
