# Generated by Django 4.2.6 on 2024-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0003_alter_caracteristicas_infancia_adolescencia_hc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caracteristicas_infancia_adolescencia',
        ),
    ]
