# Generated by Django 4.2.6 on 2024-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0005_modalidad_sentimientos_modalidad_sensaciones_fisicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='edad_casar_padres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
