# Generated by Django 4.2.6 on 2024-11-04 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_psicologica_app', '0004_atencion_psicologica_observaciones'),
        ('historia_clinica_app', '0009_historia_clinica_cuales_pensamto_vuelven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica'),
        ),
    ]
