# Generated by Django 4.2.6 on 2024-11-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_psicologica_app', '0004_atencion_psicologica_observaciones'),
        ('persona_app', '0007_alter_persona_direccion'),
        ('historia_clinica_app', '0010_alter_historia_clinica_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='aplicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='atencion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica'),
        ),
    ]
