# Generated by Django 4.2.6 on 2024-11-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('religion_app', '0001_initial'),
        ('vive_con_app', '0001_initial'),
        ('municipio_app', '0001_initial'),
        ('vive_en_app', '0001_initial'),
        ('grado_academico_app', '0001_initial'),
        ('licenciatura_app', '0002_licenciatura_tipo_licenciatura'),
        ('estado_app', '0001_initial'),
        ('estado_civil_app', '0001_initial'),
        ('historia_clinica_app', '0011_alter_historia_clinica_aplicado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenciatura_app.licenciatura'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_civil_app.estado_civil'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='estado_nac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='grado_est',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grado_academico_app.grado_academico'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='municipio_nac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipio_app.municipio'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='religion_app.religion'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='vive_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vive_con_app.vive_con'),
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='vive_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vive_en_app.vive_en'),
        ),
    ]
