# Generated by Django 4.2.6 on 2024-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0012_alter_historia_clinica_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinica',
            name='vive_en',
        ),
    ]
