# Generated by Django 4.2.6 on 2024-11-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vive_en_app', '0002_alter_vive_en_estado'),
        ('historia_clinica_app', '0013_remove_historia_clinica_vive_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia_clinica',
            name='vive_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vive_en_app.vive_en'),
        ),
    ]
