# Generated by Django 4.2.6 on 2024-11-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0015_alter_caracteristicas_infancia_adolescencia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia_clinica',
            name='detalle_primera_exp_sexual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
