# Generated by Django 4.2.6 on 2024-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0016_historia_clinica_detalle_primera_exp_sexual'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia_clinica',
            name='menst_afecta_animo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
