# Generated by Django 4.2.6 on 2024-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica_app', '0017_historia_clinica_menst_afecta_animo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia_clinica',
            name='hc_cerrada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
