# Generated by Django 4.2.6 on 2024-06-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona_app', '0007_alter_persona_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'Modalidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='taller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('estado', models.CharField(default=False, max_length=255, verbose_name='Estado')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller_app.modalidad')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'Taller',
                'ordering': ['nombre'],
            },
        ),
    ]
