# Generated by Django 4.2.6 on 2024-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_app', '0002_alter_taller_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='especialista',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialista'),
        ),
    ]
