# Generated by Django 4.2.6 on 2024-04-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion_psicologica_app', '0002_alter_atencion_psicologica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='disponibilidad_horario_consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=255, verbose_name='Dia')),
                ('hora', models.CharField(max_length=255, verbose_name='Hora')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica')),
            ],
            options={
                'verbose_name': 'disponibilidad_horario_consulta',
                'verbose_name_plural': 'Disponibilidad Horario Consulta',
                'ordering': ['id'],
            },
        ),
    ]
