# Generated by Django 4.2.6 on 2024-03-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion_psicologica_app', '0002_alter_atencion_psicologica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivo_consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_uno', models.CharField(max_length=255, verbose_name='Pregunta uno')),
                ('pregunta_dos', models.CharField(max_length=255, verbose_name='Pregunta dos')),
                ('pregunta_tres', models.CharField(max_length=255, verbose_name='Pregunta tres')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica')),
            ],
            options={
                'verbose_name': 'motivo_consulta',
                'verbose_name_plural': 'Motivo de Consulta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='horario_motivo_consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=255, verbose_name='Dia')),
                ('hora', models.CharField(max_length=255, verbose_name='Hora')),
                ('motivo_consulta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='motivo_consulta_app.motivo_consulta')),
            ],
            options={
                'verbose_name': 'horario_motivo_consulta',
                'verbose_name_plural': 'Horario Motivo de Consulta',
                'ordering': ['motivo_consulta'],
            },
        ),
    ]
