# Generated by Django 4.2.6 on 2024-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo_consulta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_motivo_consulta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motivo_consulta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
