# Generated by Django 4.2.6 on 2024-04-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_psicologica_app', '0002_alter_atencion_psicologica_options'),
        ('seguimiento_atencion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento_atencion',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica'),
        ),
    ]
