# Generated by Django 4.2.6 on 2024-02-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipio_app', '0001_initial'),
        ('grado_academico_app', '0001_initial'),
        ('ingreso_familiar_app', '0001_initial'),
        ('semestre_app', '0001_initial'),
        ('estado_app', '0001_initial'),
        ('licenciatura_app', '0002_licenciatura_tipo_licenciatura'),
        ('vive_con_app', '0001_initial'),
        ('persona_app', '0007_alter_persona_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion_psicologica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha atencion')),
                ('hijos', models.BooleanField(default=True)),
                ('trabaja', models.BooleanField(default=True)),
                ('beca_apoyo_economico', models.BooleanField(default=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('vive_con_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('grado_academico_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
                ('grado_academico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grado_academico_app.grado_academico')),
                ('ingreso_familiar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_familiar_app.ingreso_familiar')),
                ('licenciatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='licenciatura_app.licenciatura')),
                ('municipio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='municipio_app.municipio')),
                ('semestre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='semestre_app.semestre')),
                ('solicitante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona')),
                ('vive_con', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vive_con_app.vive_con')),
            ],
            options={
                'verbose_name': 'atencion_psicologica',
                'verbose_name_plural': 'Atención Psocologica',
                'ordering': ['fecha_atencion'],
            },
        ),
    ]
