# Generated by Django 4.2.6 on 2024-06-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_app', '0001_initial'),
        ('atencion_psicologica_app', '0002_alter_atencion_psicologica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion_diagnostico_dsm5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion_psicologica_app.atencion_psicologica')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostico_app.diagnostico')),
            ],
            options={
                'verbose_name': 'atencion_diagnostico_dsm5',
                'verbose_name_plural': 'atencion_diagnostico_dsm5',
                'ordering': ['atencion'],
            },
        ),
        migrations.AddField(
            model_name='atencion_psicologica',
            name='diagnostico',
            field=models.ManyToManyField(through='atencion_psicologica_app.atencion_diagnostico_dsm5', to='diagnostico_app.diagnostico'),
        ),
    ]
