# Generated by Django 4.2.6 on 2024-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_psicologica_app', '0003_atencion_diagnostico_dsm5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion_psicologica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
