# Generated by Django 4.2.6 on 2024-11-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vive_con_app', '0001_initial'),
        ('grado_academico_app', '0001_initial'),
        ('atencion_psicologica_app', '0004_atencion_psicologica_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion_psicologica',
            name='grado_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grado_academico_app.grado_academico'),
        ),
        migrations.AlterField(
            model_name='atencion_psicologica',
            name='vive_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vive_con_app.vive_con'),
        ),
    ]
