# Generated by Django 4.2.6 on 2023-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingreso_familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.CharField(max_length=255, null=True, verbose_name='Ingresos Familiares Mensuales')),
                ('nivel', models.CharField(max_length=255, verbose_name='Nivel')),
                ('color', models.CharField(max_length=255, verbose_name='Color definido')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'ingreso_familiar',
                'verbose_name_plural': 'Ingresos familiares',
                'ordering': ['ingreso'],
            },
        ),
    ]
